<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.04400000000000001" tests="30" failures="10">
  <testsuite name="Root Suite" timestamp="2020-07-10T10:45:08" tests="0" failures="0" time="0">
  </testsuite>
  <testsuite name="Arithmetic" timestamp="2020-07-10T10:45:08" tests="0" file="/Users/kevinalwell/Desktop/solutions_engineering/twitch/node-calculator/test/arithmetic.js" failures="0" time="0">
  </testsuite>
  <testsuite name="Validation" timestamp="2020-07-10T10:45:08" tests="6" file="/Users/kevinalwell/Desktop/solutions_engineering/twitch/node-calculator/test/arithmetic.js" failures="0" time="0.02600000000000001">
    <testcase name="Arithmetic Validation rejects missing operation" time="0.016" classname="rejects missing operation">
    </testcase>
    <testcase name="Arithmetic Validation rejects invalid operation" time="0.002" classname="rejects invalid operation">
    </testcase>
    <testcase name="Arithmetic Validation rejects missing operand1" time="0.002" classname="rejects missing operand1">
    </testcase>
    <testcase name="Arithmetic Validation rejects missing operand2" time="0.002" classname="rejects missing operand2">
    </testcase>
    <testcase name="Arithmetic Validation rejects operands with invalid sign" time="0.002" classname="rejects operands with invalid sign">
    </testcase>
    <testcase name="Arithmetic Validation rejects operands with invalid decimals" time="0.002" classname="rejects operands with invalid decimals">
    </testcase>
  </testsuite>
  <testsuite name="Addition" timestamp="2020-07-10T10:45:09" tests="6" file="/Users/kevinalwell/Desktop/solutions_engineering/twitch/node-calculator/test/arithmetic.js" failures="0" time="0.008">
    <testcase name="Arithmetic Addition adds two positive integers" time="0.002" classname="adds two positive integers">
    </testcase>
    <testcase name="Arithmetic Addition adds zero to an integer" time="0.001" classname="adds zero to an integer">
    </testcase>
    <testcase name="Arithmetic Addition adds a negative integer to a positive integer" time="0.002" classname="adds a negative integer to a positive integer">
    </testcase>
    <testcase name="Arithmetic Addition adds two negative integers" time="0.001" classname="adds two negative integers">
    </testcase>
    <testcase name="Arithmetic Addition adds an integer to a floating point number" time="0.001" classname="adds an integer to a floating point number">
    </testcase>
    <testcase name="Arithmetic Addition adds with negative exponent" time="0.001" classname="adds with negative exponent">
    </testcase>
  </testsuite>
  <testsuite name="Subtraction" timestamp="2020-07-10T10:45:09" tests="5" file="/Users/kevinalwell/Desktop/solutions_engineering/twitch/node-calculator/test/arithmetic.js" failures="4" time="0.001">
    <testcase name="Arithmetic Subtraction subtracts two positive integers" time="0" classname="subtracts two positive integers">
      <failure message="expected { result: 22 } to deeply equal { result: 21 }" type="AssertionError"><![CDATA[AssertionError: expected { result: 22 } to deeply equal { result: 21 }
    at Test.<anonymous> (test/arithmetic.js:109:35)
    at Test.assert (node_modules/supertest/lib/test.js:181:6)
    at Server.localAssert (node_modules/supertest/lib/test.js:131:12)
    at emitCloseNT (net.js:1653:8)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)]]></failure>
    </testcase>
    <testcase name="Arithmetic Subtraction subtracts an integer from itself" time="0" classname="subtracts an integer from itself">
      <failure message="expected { result: 1 } to deeply equal { result: 0 }" type="AssertionError"><![CDATA[AssertionError: expected { result: 1 } to deeply equal { result: 0 }
    at Test.<anonymous> (test/arithmetic.js:117:35)
    at Test.assert (node_modules/supertest/lib/test.js:181:6)
    at Server.localAssert (node_modules/supertest/lib/test.js:131:12)
    at emitCloseNT (net.js:1653:8)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)]]></failure>
    </testcase>
    <testcase name="Arithmetic Subtraction subtracts a larger integer from another" time="0" classname="subtracts a larger integer from another">
      <failure message="expected { result: -20 } to deeply equal { result: -21 }" type="AssertionError"><![CDATA[AssertionError: expected { result: -20 } to deeply equal { result: -21 }
    at Test.<anonymous> (test/arithmetic.js:125:35)
    at Test.assert (node_modules/supertest/lib/test.js:181:6)
    at Server.localAssert (node_modules/supertest/lib/test.js:131:12)
    at emitCloseNT (net.js:1653:8)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)]]></failure>
    </testcase>
    <testcase name="Arithmetic Subtraction subtracts a negative integer from a positive integer" time="0" classname="subtracts a negative integer from a positive integer">
      <failure message="expected { result: 43 } to deeply equal { result: 42 }" type="AssertionError"><![CDATA[AssertionError: expected { result: 43 } to deeply equal { result: 42 }
    at Test.<anonymous> (test/arithmetic.js:133:35)
    at Test.assert (node_modules/supertest/lib/test.js:181:6)
    at Server.localAssert (node_modules/supertest/lib/test.js:131:12)
    at emitCloseNT (net.js:1653:8)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)]]></failure>
    </testcase>
    <testcase name="Arithmetic Subtraction subtracts an integer from a floating point number" time="0.001" classname="subtracts an integer from a floating point number">
    </testcase>
  </testsuite>
  <testsuite name="Multiplication" timestamp="2020-07-10T10:45:09" tests="6" file="/Users/kevinalwell/Desktop/solutions_engineering/twitch/node-calculator/test/arithmetic.js" failures="0" time="0.007">
    <testcase name="Arithmetic Multiplication multiplies two positive integers" time="0.001" classname="multiplies two positive integers">
    </testcase>
    <testcase name="Arithmetic Multiplication multiplies a positive integer with zero" time="0.001" classname="multiplies a positive integer with zero">
    </testcase>
    <testcase name="Arithmetic Multiplication multiplies a positive integer and negative integer" time="0.001" classname="multiplies a positive integer and negative integer">
    </testcase>
    <testcase name="Arithmetic Multiplication multiplies two negative integers" time="0.001" classname="multiplies two negative integers">
    </testcase>
    <testcase name="Arithmetic Multiplication multiplies two floating point numbers" time="0.001" classname="multiplies two floating point numbers">
    </testcase>
    <testcase name="Arithmetic Multiplication multiplies supporting exponential notation" time="0.002" classname="multiplies supporting exponential notation">
    </testcase>
  </testsuite>
  <testsuite name="Division" timestamp="2020-07-10T10:45:09" tests="7" file="/Users/kevinalwell/Desktop/solutions_engineering/twitch/node-calculator/test/arithmetic.js" failures="6" time="0.002">
    <testcase name="Arithmetic Division divides a positive integer by an integer factor " time="0" classname="divides a positive integer by an integer factor ">
      <failure message="expected { result: 20 } to deeply equal { result: 21 }" type="AssertionError"><![CDATA[AssertionError: expected { result: 20 } to deeply equal { result: 21 }
    at Test.<anonymous> (test/arithmetic.js:203:35)
    at Test.assert (node_modules/supertest/lib/test.js:181:6)
    at Server.localAssert (node_modules/supertest/lib/test.js:131:12)
    at emitCloseNT (net.js:1653:8)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)]]></failure>
    </testcase>
    <testcase name="Arithmetic Division divides a negative integer by an integer factor " time="0" classname="divides a negative integer by an integer factor ">
      <failure message="expected { result: -22 } to deeply equal { result: -21 }" type="AssertionError"><![CDATA[AssertionError: expected { result: -22 } to deeply equal { result: -21 }
    at Test.<anonymous> (test/arithmetic.js:211:35)
    at Test.assert (node_modules/supertest/lib/test.js:181:6)
    at Server.localAssert (node_modules/supertest/lib/test.js:131:12)
    at emitCloseNT (net.js:1653:8)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)]]></failure>
    </testcase>
    <testcase name="Arithmetic Division divides a positive integer by a non-factor" time="0" classname="divides a positive integer by a non-factor">
      <failure message="expected { result: -0.5 } to deeply equal { result: 0.5 }" type="AssertionError"><![CDATA[AssertionError: expected { result: -0.5 } to deeply equal { result: 0.5 }
    at Test.<anonymous> (test/arithmetic.js:219:35)
    at Test.assert (node_modules/supertest/lib/test.js:181:6)
    at Server.localAssert (node_modules/supertest/lib/test.js:131:12)
    at emitCloseNT (net.js:1653:8)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)]]></failure>
    </testcase>
    <testcase name="Arithmetic Division divides a positive integer by a negative integer" time="0" classname="divides a positive integer by a negative integer">
      <failure message="expected { result: -1.5 } to deeply equal { result: -0.5 }" type="AssertionError"><![CDATA[AssertionError: expected { result: -1.5 } to deeply equal { result: -0.5 }
    at Test.<anonymous> (test/arithmetic.js:227:35)
    at Test.assert (node_modules/supertest/lib/test.js:181:6)
    at Server.localAssert (node_modules/supertest/lib/test.js:131:12)
    at emitCloseNT (net.js:1653:8)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)]]></failure>
    </testcase>
    <testcase name="Arithmetic Division divides zero by a positive integer" time="0" classname="divides zero by a positive integer">
      <failure message="expected { result: -1 } to deeply equal { result: 0 }" type="AssertionError"><![CDATA[AssertionError: expected { result: -1 } to deeply equal { result: 0 }
    at Test.<anonymous> (test/arithmetic.js:235:35)
    at Test.assert (node_modules/supertest/lib/test.js:181:6)
    at Server.localAssert (node_modules/supertest/lib/test.js:131:12)
    at emitCloseNT (net.js:1653:8)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)]]></failure>
    </testcase>
    <testcase name="Arithmetic Division divides by zero" time="0" classname="divides by zero">
      <failure message="expected { result: -0.75 } to deeply equal { result: 0.25 }" type="AssertionError"><![CDATA[AssertionError: expected { result: -0.75 } to deeply equal { result: 0.25 }
    at Test.<anonymous> (test/arithmetic.js:243:35)
    at Test.assert (node_modules/supertest/lib/test.js:181:6)
    at Server.localAssert (node_modules/supertest/lib/test.js:131:12)
    at emitCloseNT (net.js:1653:8)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)]]></failure>
    </testcase>
    <testcase name="Arithmetic Division divides by zero" time="0.002" classname="divides by zero">
    </testcase>
  </testsuite>
</testsuites>